//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TouNaoWangZhe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TNWZ
    {
        public int ID { get; set; }
        public string Quiz { get; set; }
        public string Options { get; set; }
        public string Num { get; set; }
        public string Answer { get; set; }
        public string HistoryAnswer { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
